### ISSUE TITLE
Can list private resources

### ISSUE THREAD

**Issue by mzur** [ArunaStorage/DataProxy#54]
Maybe related to https://github.com/ArunaStorage/ArunaWeb/issues/72

I can list private projects, collections and objects via S3. Only the object size is not shown correctly (it says 0 in the s5cmd output). If I try to download a private object, the download hangs first and then says:

```
ERROR "cp s3://my-little-project/my-little-project/my-little-collection/sample.fastq.tar.gz sample.fastq.tar.gz": InternalError: Object location not found status code: 500, request id: , host id:
```

Note that I had to repeat the project/bucket name `my-little-project/my-little-project` in order to list the resources via S3 (otherwise I get "no object found"). Maybe this is a separate issue.

If I try to download the object from `s3://my-little-project/my-little-collection/sample.fastq.tar.gz sample.fastq.tar.gz` (only one bucket name), I get a (correct?) "AccessDenied".

**Comment by St4NNi** [comment]
Thanks for reporting, this indeed sounds weird. Just a quick check are you the owner of "my-little-project"?
In any case we will have a deeper look at this.

**Comment by mzur** [comment]
No, I'm not the owner of "my-little-project". But in https://github.com/ArunaStorage/ArunaWeb/issues/72 it was explained that "private" does not mean "hidden" but rather "restricted". So I can see all private resources but I can't download them without permission. So maybe the S3 interface works as intended here (except maybe that another status code should be returned).

**Comment by St4NNi** [comment]
Ok, so this is 100% a bug. The `data plane` should handle permissions completely separate from the `metadata plane`. Private buckets & objects should not be accessible nor findable ("hidden") from an S3 perspective for people without access.

The rules described in (ArunaStorage/ArunaWeb#72) should only apply to a limited view in the search section for discoverability purposes and not extend to the data level.

**Comment by das-Abroxas** [comment]
It seems that 1e2a149 (I've no idea why exactly this one commit isn't signed :roll_eyes:) has fixed the problem. 

Basically, the bug did not result in someone having unauthorized access to other users' resources, but was just an unfortunate error message due to incorrect permission handling of non-existent resources.

If I now repeat your request, I get the following error message that the resource does not exist:
```
ERROR "cp s3://my-little-project/my-little-project/my-little-collection/sample.fastq.tar.gz sample.fastq.tar.gz": AccessDenied : Invalid access key status code: 403
```

If I try to access a resource which I do not have permissions for, I get the following access denied error message:
```
ERROR "cp s3://biigletest/biiglecollection/160-1_OFOS-11_subset/SO268-2_160-1_OFOS_SO_CAM-1_20190427_181912.JPG SO268-2_160-1_OFOS_SO_CAM-1_20190427_181912.JPG": AccessDenied : Access denied status code: 403
```

I will close the issue as resolved. If further questions arise, the issue can be reopened.
