### ISSUE TITLE
Broken Ranges

### ISSUE THREAD

**Issue by St4NNi** [ArunaStorage/DataProxy#56]
Range request will sometimes result in too few bytes resulting in an EOF error.

The appropriate application of the internal filtering have to be checked.

**Comment by das-Abroxas** [comment]
Forgot to mention the issue in the commit, so here's a quick update. The problem should finally be fixed with the commit c295320b24081023eada7bd800d173e2edbf4f6f. 

In addition, a fallback mechanism has been implemented that allows range requests to work against large files that (for whatever reason) do not have an aruna-file footer.

I will close the issue for now.
